### ISSUE TITLE
Any plan to support Nvidia Jetson XX family?

### ISSUE THREAD

**Issue by ksachdeva** [microsoft/superbenchmark#379]
**What would you like to be added**:

Support for nvidia Jetson devices

**Why is this needed**:

ML model execution of edge devices (nvidia jetson)

**Comment by cp5555** [comment]
Thanks for your suggestion, Kapil. SuperBench mainly focus on Cloud GPUs for both training and inference and we don't have plan to support edge GPU officially now. I think Jetson should support CUDA, if so, you can run SuperBench on it directly. If you have interests, please feel free to submit PR on our repo to support Jetson devices.

**Comment by cp5555** [comment]
Thanks again for your suggestion, @ksachdeva. Do you have any more suggestions or comments? If not, I will close this issue.
