### ISSUE TITLE
superbench logging: 'color' output should be optional

### ISSUE THREAD

**Issue by LiweiPeng** [microsoft/superbenchmark#400]
In current [superbench code](https://github.com/microsoft/superbenchmark/blob/main/superbench/common/utils/logging.py#L74), the logger has a hard-coded 'color' mode. While this design is good for interactive mode, it is bad when processing the logs programmatically in system like Geneva.

The following is superbench output's raw text:
^[[0;33m[1,4]<stdout>:^[[0m[^[[36m2022-08-29 22:50:16,377 node1:287^[[0m][^[[34mexecutor.py:125^[[0m][^[[32mINFO^[[0m] Executor succeeded in nccl-bw:nvlink.^[[0m^[[0m^M

Expected: the color mode should be an option to 'sb' command. or it can be turned off by some environmental variable.
The following is the expectd raw text:

[1,4]<stdout>:[2022-08-29 22:50:16,377 ND40rsv201000009:287][executor.py:125][INFO] Executor succeeded in nccl-bw:nvlink.

**Comment by abuccts** [comment]
* For logs directly written to file (sb-run.log, sb-exec.log), there's no color by default
* For logs written to stdout/stderr, you can disable it with `ANSIBLE_NOCOLOR=1` and `NO_COLOR=1`

**Comment by LiweiPeng** [comment]
where to set these env variables? When I set them on the console like below. the output still has colors

export ANSIBLE_NOCOLOR=1
export NO_COLOR=1
sb run -f local.ini -c debug/run1.yaml

![image](https://user-images.githubusercontent.com/8562078/187742428-e75b64b5-9c6b-4b9c-a9a7-23d5f6fc326c.png)

**Comment by abuccts** [comment]
did you try with the latest [release/0.6](https://github.com/microsoft/superbenchmark/tree/release/0.6) branch? will need to pull the code and rerun `python3 -m pip install .` on management node

**Comment by LiweiPeng** [comment]
fixed with latest PR.
