### ISSUE TITLE
why '/dev/nvidia-uvm' is a required file check for nvidia GPU?

### ISSUE THREAD

**Issue by LiweiPeng** [microsoft/superbenchmark#412]
**What's the issue, what's expected?**:
This is v0.6.0. In (superbench code gpu.py) [(https://github.com/microsoft/superbenchmark/blob/main/superbench/common/devices/gpu.py#L24), it checks whether a GPU is nvidia by checking both '/dev/nvidiactl' and '/dev/nvidia-uvm'.  The question is: why does it require /dev/nvidia-uvm? I found some GPU type like 'Tesla K80' with cuda 11.4 doesn't have this.

**How to reproduce it?**:
Logon to a machine with  'Tesla K80' + cuda 11.4.

**Comment by abuccts** [comment]
It's required when using gpus in docker, and should be included as one step during [nvidia driver installation](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile-verifications)

If you cannot find /dev/nvidia-uvm in your system, you can run following commands to create it accroding to above document:
```bash
/sbin/modprobe nvidia-uvm
D=`grep nvidia-uvm /proc/devices | awk '{print $1}'`
mknod -m 666 /dev/nvidia-uvm c $D 0
```

**Comment by LiweiPeng** [comment]
Because K80 GPU is not supported by superbench, it is OK not to support it.
