### ISSUE TITLE
Passing multiple test configurations to cublas microbenchmark

### ISSUE THREAD

**Issue by yupei-ms** [microsoft/superbenchmark#413]
**What would you like to be added**:
Support multiple configurations as a list in the YAML config file for cublas testing

**Why is this needed**:
Can create a sweep of custom tests to run

**Without this feature, how does current superbenchmark work**：
Use the default list of test configs or pass only 1 test config

**Components that may involve changes**:
The logic in https://github.com/microsoft/superbenchmark/blob/main/superbench/benchmarks/micro_benchmarks/cublas_function.py#L248
that can handle a list of different dictionaries 

**Brief description of your proposal if any**:

**Comment by yukirora** [comment]
Thanks for reaching out this issue to us, we will prepare a pr to fix it soon

**Comment by yukirora** [comment]
#414 is to solve this issue
