### ISSUE TITLE
Executor/Run benchmark failed messages while running bert-large model with superbench

### ISSUE THREAD

**Issue by pnunna93** [microsoft/superbenchmark#471]
**What's the issue, what's expected?**:
bert-large model failed with error messages show below when tried to run with superbench on A100-80GB machine with 8 GPUs. Please help provide suggestions to fix this.

**How to reproduce it?**:
Run Command:
sb run --no-docker -l localhost -c <config file> --output-dir <output path>

**Log message or shapshot?**:
 Model placement - model: pytorch-bert-large, GPU availablility: True, pin memory: True, force fp32: False.[0m
 Distributed training is enabled - model: pytorch-bert-large, distributed implementation: ddp.[0m
 Executor is going to execute bert_models/pytorch-bert-large.[0m
 Model placement - model: pytorch-bert-large, GPU availablility: True, pin memory: True, force fp32: False.[0m
 Distributed training is enabled - model: pytorch-bert-large, distributed implementation: ddp.[0m
 Run benchmark failed - benchmark: pytorch-bert-large, message: Broken pipe[0m
 benchmark: pytorch-bert-large, return code: 4, result: {'return_code': [4]}.[0m
 Executor failed in bert_models/pytorch-bert-large.[0m
 Run benchmark failed - benchmark: pytorch-bert-large, message: Broken pipe[0m
 benchmark: pytorch-bert-large, return code: 4, result: {'return_code': [4]}.[0m
 Executor failed in bert_models/pytorch-bert-large.[0m
 benchmark: pytorch-bert-base, return code: 0, result: {'return_code': [0]}.[0m
 Executor succeeded in bert_models/pytorch-bert-base.[0m
 Run benchmark failed - benchmark: pytorch-bert-large, message: Broken pipe[0m
 benchmark: pytorch-bert-large, return code: 4, result: {'return_code': [4]}.[0m
 Executor failed in bert_models/pytorch-bert-large.[0m
 Executor is going to execute bert_models/pytorch-bert-large.[0m
 Model placement - model: pytorch-bert-large, GPU availablility: True, pin memory: True, force fp32: False.[0m
 Distributed training is enabled - model: pytorch-bert-large, distributed implementation: ddp.[0m
 benchmark: pytorch-bert-base, return code: 0, result: {'return_code': [0]}.[0m
 Executor succeeded in bert_models/pytorch-bert-base.[0m
 Executor is going to execute bert_models/pytorch-bert-large.[0m
 benchmark: pytorch-bert-base, return code: 0, result: {'return_code': [0], 'fp32_train_step_time': [96.17431712523103], 'fp32_train_throughput': [333.46321017523894], 'fp16_train_step_time': [66.33570070005953], 'fp16_train_throughput': [484.904031859023]}.[0m
 Executor succeeded in bert_models/pytorch-bert-base.[0m
 Model placement - model: pytorch-bert-large, GPU availablility: True, pin memory: True, force fp32: False.[0m
 Distributed training is enabled - model: pytorch-bert-large, distributed implementation: ddp.[0m
 benchmark: pytorch-bert-base, return code: 0, result: {'return_code': [0]}.[0m
 Executor succeeded in bert_models/pytorch-bert-base.[0m
 Executor is going to execute bert_models/pytorch-bert-large.[0m
 Model placement - model: pytorch-bert-large, GPU availablility: True, pin memory: True, force fp32: False.[0m
 Distributed training is enabled - model: pytorch-bert-large, distributed implementation: ddp.[0m
 Executor is going to execute bert_models/pytorch-bert-large.[0m
 Model placement - model: pytorch-bert-large, GPU availablility: True, pin memory: True, force fp32: False.[0m
 Distributed training is enabled - model: pytorch-bert-large, distributed implementation: ddp.[0m
 Run benchmark failed - benchmark: pytorch-bert-large, message: Timed out initializing process group in store based barrier on rank: 1, for key: store_based_barrier_key:1 (world_size=8, worker_count=4, timeout=0:05:00)[0m
 benchmark: pytorch-bert-large, return code: 4, result: {'return_code': [4]}.[0m
 Executor failed in bert_models/pytorch-bert-large.[0m
 Run benchmark failed - benchmark: pytorch-bert-large, message: Timed out initializing process group in store based barrier on rank: 2, for key: store_based_barrier_key:1 (world_size=8, worker_count=4, timeout=0:05:00)[0m
 benchmark: pytorch-bert-large, return code: 4, result: {'return_code': [4]}.[0m
 Executor failed in bert_models/pytorch-bert-large.[0m
 Run benchmark failed - benchmark: pytorch-bert-large, message: Timed out initializing process group in store based barrier on rank: 4, for key: store_based_barrier_key:1 (world_size=8, worker_count=4, timeout=0:05:00)[0m
 benchmark: pytorch-bert-large, return code: 4, result: {'return_code': [4]}.[0m
 Executor failed in bert_models/pytorch-bert-large.[0m
 Run benchmark failed - benchmark: pytorch-bert-large, message: Timed out initializing process group in store based barrier on rank: 7, for key: store_based_barrier_key:1 (world_size=8, worker_count=4, timeout=0:05:00)[0m
 benchmark: pytorch-bert-large, return code: 4, result: {'return_code': [4]}.[0m
 Executor failed in bert_models/pytorch-bert-large.[0m
 Run benchmark failed - benchmark: pytorch-bert-large, message: Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=8, worker_count=5, timeout=0:05:00)[0m
 benchmark: pytorch-bert-large, return code: 4, result: {'return_code': [4]}.[0m
 Executor failed in bert_models/pytorch-bert-large.[0m/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated

**Additional information**:

**Comment by abuccts** [comment]
Hi, could you please share the full command and corresponding config file? seems some parameters in the provided command `sb run --no-docker -l localhost -c --output-dir` are omitted.

Besides, were you running on host directly or manually started a Docker container before running (if so, could you provide the command as well)? We only tested benchmarks in the [SuperBench Docker images](https://microsoft.github.io/superbenchmark/docs/user-tutorial/container-images#stable-tagged-versions) and they're not guaranteed in arbitrary environments.

**Comment by pnunna93** [comment]
Opened separate issue for this, closing this one.
