### ISSUE TITLE
[Bug] ansible_runner updated to 2.3.2 last week, superbench fails with python 3.6 

### ISSUE THREAD

**Issue by Blackhawk95** [microsoft/superbenchmark#484]
**What's the issue, what's expected?**:
`from __future__ import annotations` is added to [2.3.2](https://github.com/ansible/ansible-runner/compare/2.3.1...2.3.2#diff-81c3df3f520280c8548b6499f287446e289a81ecad30288e0c561d3aa95456c5) version of ansible_runner, which seems to be only supported on python 3.7+

**How to reproduce it?**:
Build superbench on ubuntu 18.04 docker image ( Ubuntu 18.04 by default comes with python 3.6 )

**Comment by abuccts** [comment]
Fixed in #485, pls have a try, thanks for your contribution

**Comment by Blackhawk95** [comment]
Hi @abuccts, Thanks for the update. I believe this fix doesn't help any of the existing releases.

**Comment by abuccts** [comment]
Hi @Blackhawk95, sorry for the late response.

For the pre-built Docker images and `sb` inside those images, you can use the previous releases directly.
If you need to build the tool with pip, you will need to use the new release (e.g., v0.8.0) or latest main branch.
