### ISSUE TITLE
Some test does not support CS 8.9(RTX 4080/4090)

### ISSUE THREAD

**Issue by edisonchan** [microsoft/superbenchmark#521]
**What's the issue, what's expected?**:
[2023-04-16 12:26:24,006 u22:880][cuda_gemm_flops_performance.py:77][ERROR] Unsupported architecture - benchmark: gemm-flops, compute capability: 8.9, supports 7.0 7.5 8.0 8.6 9.0

**How to reproduce it?**:
Run superbenchmark with RTX 4080/4090.

**Log message or shapshot?**:
![image](https://user-images.githubusercontent.com/8596506/232312105-ee22fe62-9a7d-4b84-8d58-013c92006458.png)

**Additional information**:

[sb-exec.log](https://github.com/microsoft/superbenchmark/files/11242430/sb-exec.log)

**Comment by cp5555** [comment]
Sorry. SuperBenchmark doesn't officially support GeForce series at all. Also, we don't have plan to support that architecture as well.

**Comment by cp5555** [comment]
Hi @edisonchan, do you have any other questions? If not, we will close this issue.
