### ISSUE TITLE
Superbench result contains null characters.

### ISSUE THREAD

**Issue by Qingshengh** [microsoft/superbenchmark#535]
**What's the issue, what's expected?**:
when run superbench in container, the result contains some null characters.

**How to reproduce it?**:
run command:
sb run -l localhost --no-docker -c /opt/superbench/config.yaml --output-dir $Output 

**Log message or shapshot?**:
can contact 'qingh@microsoft.com' to get full logs.
localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
[0m[[36m2023-06-01 03:49:12,982 superbench-fxdc6:34[0m][[34mansible.py:79[0m][[32mINFO[0m] Run succeed, return code 0.[0m
                                             

**Additional information**:

**Comment by guoshzhao** [comment]
Confirmed that it's related with storage not related with Superbench.
