### ISSUE TITLE
out-of-date reference link

### ISSUE THREAD

**Issue by quge009** [microsoft/superbenchmark#537]
**What's the issue, what's expected?**:
opening the reference link of (https://huggingface.co/transformers/model_doc/gpt2.html) in https://github.com/microsoft/superbenchmark/blob/a1cd3c94750631a0ac6a01b93a234500a0d6838f/superbench/benchmarks/model_benchmarks/pytorch_gpt2.py#LL74C1-L74C86
is 404

**How to reproduce it?**:
open the link

**Log message or shapshot?**:
404

**Additional information**:
manually check the link seems to to updated to 
https://huggingface.co/docs/transformers/model_doc/gpt2

**Comment by cp5555** [comment]
Thanks for your suggestion. We solve it  in PR #539
