### ISSUE TITLE
Error: parsing sudo passwords containing special symbols

### ISSUE THREAD

**Issue by quge009** [microsoft/superbenchmark#553]
**What's the issue, what's expected?**:
Executing `sb deploy` with  `--host-password [P]` generates wrong command parsing result, when [P] contains '!'
Executing `sb deploy` with  `--host-password [P]` will hang in [COPY] task, when [P] contains '$'

**How to reproduce it?**:
run sb deploy with password contain '!' or '$'

**Log message or shapshot?**:
![image](https://github.com/microsoft/superbenchmark/assets/59161330/4bd14086-5275-4991-8d5d-127786aeb4ee)

**Additional information**:
N/A

**Comment by abuccts** [comment]
It's by design in bash, you need to either enclose the string by `''` (e.g., --password '!$') or escape them with `\` (e.g., --password \!\$) https://stackoverflow.com/a/51828135/7630831.
