### ISSUE TITLE
Urgent: while executing the superbench, it's failing (UBUNTU)

### ISSUE THREAD

**Issue by pawarsc** [microsoft/superbenchmark#561]
**What's the issue, what's expected?**:
[ansible.py:74][INFO] Run as sudo ...
localhost | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "sudo: a password is required\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
localhost | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "sudo: a password is required\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
localhost | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "sudo: a password is required\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
localhost | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "sudo: a password is required\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
localhost | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "sudo: a password is required\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
localhost | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "sudo: a password is required\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
localhost | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "sudo: a password is required\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
localhost | FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python3"
    },
    "changed": false,
    "module_stderr": "sudo: a password is required\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
[2023-09-13 07:17:18,374 demo:46152][ansible.py:83][WARNING] Run failed, return code 2.
[2023-09-13 07:17:18,380 demo:46146][ansible.py:83][WARNING] Run failed, return code 2.
[2023-09-13 07:17:18,383 demo:46149][ansible.py:83][WARNING] Run failed, return code 2.
[2023-09-13 07:17:18,397 demo:46153][ansible.py:83][WARNING] Run failed, return code 2.
[2023-09-13 07:17:18,413 demo:46148][ansible.py:83][WARNING] Run failed, return code 2.
[2023-09-13 07:17:18,415 demo:46147][ansible.py:83][WARNING] Run failed, return code 2.
[2023-09-13 07:17:18,423 demo:46150][ansible.py:83][WARNING] Run failed, return code 2.
[2023-09-13 07:17:18,429 demo:46151][ansible.py:83][WARNING] Run failed, return code 2.
[2023-09-13 07:17:18,431 demo:44237][ansible.py:128][INFO] Run playbook cleanup.yaml ...

PLAY [Runtime Environment Cleanup] *********************************************

TASK [Killing sb exec processes] ***********************************************
fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
[2023-09-13 07:17:19,085 demo:44237][ansible.py:83][WARNING] Run failed, return code 2.

**How to reproduce it?**:
under GPU-VM, run SB

**Log message or shapshot?**:
copied it above

**Additional information**:
using latest cuda driver
Driver Version: 535.104.05   CUDA Version: 12.2
on UBUNTU

**Comment by abuccts** [comment]
Hi @pawarsc, sorry for the late response.

According to your log `sudo: a password is required`, seems you missed [`--host-password <your sudo password>`](https://microsoft.github.io/superbenchmark/docs/cli#sb-deploy) when running superbench commands. That argument is needed if you didn't configure passwordless sudo.

**Comment by cp5555** [comment]
@pawarsc do you still suffer this issue? If not, I will close it.
