### ISSUE TITLE
where can I get benchmark parameters definition？

### ISSUE THREAD

**Issue by homily707** [microsoft/superbenchmark#621]
**What's the issue, what's expected?**:
I want to know the parameters definitions of each benchmark, so I can modified them.
I also want to know the mode defination.
and the reason I want to modified them, is that I want to run a quick benchmark, is there a easy way to achieve this goal, rather than modified every benchmark paramaters.

**Comment by guoshzhao** [comment]
Hi @homily707,

To get the parameters definitions, you can use sb cli. The command is:
`sb benchmark list-parameters [--name]`
Please refer: https://microsoft.github.io/superbenchmark/docs/cli#sb-benchmark-list-parameters

For the mode definition, please refer our document:
https://microsoft.github.io/superbenchmark/docs/superbench-config#mode-schema

If you want to add a common parameter for all benchmarks, you can define it in the base class, for example,
For all benchmarks: https://github.com/microsoft/superbenchmark/blob/main/superbench/benchmarks/base.py
For MicroBenchmarks: https://github.com/microsoft/superbenchmark/blob/main/superbench/benchmarks/micro_benchmarks/micro_base.py
For ModelBenchmarks:
https://github.com/microsoft/superbenchmark/blob/main/superbench/benchmarks/model_benchmarks/model_base.py

If you want to quickly run the benchmark, you can refer the examples:
https://github.com/microsoft/superbenchmark/tree/main/examples/benchmarks
